import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import fs from "fs";
import path from "path";
import dotenv from "dotenv";

dotenv.config();

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/closebrackets",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/comment",
		"@codemirror/fold",
		"@codemirror/gutter",
		"@codemirror/highlight",
		"@codemirror/history",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/matchbrackets",
		"@codemirror/panel",
		"@codemirror/rangeset",
		"@codemirror/rectangular-selection",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/stream-parser",
		"@codemirror/text",
		"@codemirror/tooltip",
		"@codemirror/view",
		...builtins],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
});

const moveFiles = () => {
    const targetDir = process.env.OBSIDIAN_PLUGIN_PATH;
    if (!targetDir) {
        console.log("OBSIDIAN_PLUGIN_PATH not set in .env. Skipping file copy.");
        return;
    }

    if (!fs.existsSync(targetDir)) {
        console.log(`Target directory does not exist: ${targetDir}`);
        return;
    }

    const filesToCopy = ["main.js", "styles.css", "manifest.json"];
    filesToCopy.forEach(file => {
        fs.copyFileSync(file, path.join(targetDir, file));
        console.log(`Copied ${file} to ${targetDir}`);
    });
};

if (prod) {
	await context.rebuild();
    moveFiles();
	process.exit(0);
} else {
	await context.watch();
    // Note: watch mode doesn't easily hook into rebuild events with this setup without a plugin.
    // For simplicity, we only copy on build or we can add a plugin to esbuild context.
    // Let's add a simple plugin to copy on rebuild in watch mode.
}
